// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// updateBetaDelta_cpp
List updateBetaDelta_cpp(NumericMatrix X, NumericVector ycorr, NumericVector beta, IntegerVector delta, NumericVector pi_j, NumericVector xpx, double vare, double sigmaBetaSq);
RcppExport SEXP _BayesMAP_updateBetaDelta_cpp(SEXP XSEXP, SEXP ycorrSEXP, SEXP betaSEXP, SEXP deltaSEXP, SEXP pi_jSEXP, SEXP xpxSEXP, SEXP vareSEXP, SEXP sigmaBetaSqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ycorr(ycorrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi_j(pi_jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xpx(xpxSEXP);
    Rcpp::traits::input_parameter< double >::type vare(vareSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaBetaSq(sigmaBetaSqSEXP);
    rcpp_result_gen = Rcpp::wrap(updateBetaDelta_cpp(X, ycorr, beta, delta, pi_j, xpx, vare, sigmaBetaSq));
    return rcpp_result_gen;
END_RCPP
}
// updateDelta_cpp
IntegerVector updateDelta_cpp(IntegerVector Delta, IntegerVector delta, NumericMatrix L, IntegerVector gamma, NumericMatrix A, NumericMatrix B, double alpha1, double alpha2, double alpha3, double mu_pi, double mu_Pi, NumericVector baseline, NumericVector pathways, double rho);
RcppExport SEXP _BayesMAP_updateDelta_cpp(SEXP DeltaSEXP, SEXP deltaSEXP, SEXP LSEXP, SEXP gammaSEXP, SEXP ASEXP, SEXP BSEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP alpha3SEXP, SEXP mu_piSEXP, SEXP mu_PiSEXP, SEXP baselineSEXP, SEXP pathwaysSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type L(LSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha3(alpha3SEXP);
    Rcpp::traits::input_parameter< double >::type mu_pi(mu_piSEXP);
    Rcpp::traits::input_parameter< double >::type mu_Pi(mu_PiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type baseline(baselineSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pathways(pathwaysSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(updateDelta_cpp(Delta, delta, L, gamma, A, B, alpha1, alpha2, alpha3, mu_pi, mu_Pi, baseline, pathways, rho));
    return rcpp_result_gen;
END_RCPP
}
// updateGamma_cpp
IntegerVector updateGamma_cpp(IntegerVector gamma, IntegerVector delta, IntegerVector Delta, NumericMatrix A, NumericMatrix B, NumericMatrix L, double alpha1, double alpha2, double alpha3, double mu_pi, double mu_Pi, NumericVector baseline, NumericVector pathways, double rho);
RcppExport SEXP _BayesMAP_updateGamma_cpp(SEXP gammaSEXP, SEXP deltaSEXP, SEXP DeltaSEXP, SEXP ASEXP, SEXP BSEXP, SEXP LSEXP, SEXP alpha1SEXP, SEXP alpha2SEXP, SEXP alpha3SEXP, SEXP mu_piSEXP, SEXP mu_PiSEXP, SEXP baselineSEXP, SEXP pathwaysSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type alpha1(alpha1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha3(alpha3SEXP);
    Rcpp::traits::input_parameter< double >::type mu_pi(mu_piSEXP);
    Rcpp::traits::input_parameter< double >::type mu_Pi(mu_PiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type baseline(baselineSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pathways(pathwaysSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(updateGamma_cpp(gamma, delta, Delta, A, B, L, alpha1, alpha2, alpha3, mu_pi, mu_Pi, baseline, pathways, rho));
    return rcpp_result_gen;
END_RCPP
}
// updateZ_cpp
NumericVector updateZ_cpp(IntegerVector indicator, NumericVector eta);
RcppExport SEXP _BayesMAP_updateZ_cpp(SEXP indicatorSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type indicator(indicatorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateZ_cpp(indicator, eta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesMAP_updateBetaDelta_cpp", (DL_FUNC) &_BayesMAP_updateBetaDelta_cpp, 8},
    {"_BayesMAP_updateDelta_cpp", (DL_FUNC) &_BayesMAP_updateDelta_cpp, 14},
    {"_BayesMAP_updateGamma_cpp", (DL_FUNC) &_BayesMAP_updateGamma_cpp, 14},
    {"_BayesMAP_updateZ_cpp", (DL_FUNC) &_BayesMAP_updateZ_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesMAP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
