# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateBetaDelta_cpp <- function(X, ycorr, beta, delta, pi_j, xpx, vare, sigmaBetaSq) {
    .Call(`_BayesMAP_updateBetaDelta_cpp`, X, ycorr, beta, delta, pi_j, xpx, vare, sigmaBetaSq)
}

updateDelta_cpp <- function(Delta, delta, L, gamma, A, B, alpha1, alpha2, alpha3, mu_pi, mu_Pi, baseline, pathways, rho) {
    .Call(`_BayesMAP_updateDelta_cpp`, Delta, delta, L, gamma, A, B, alpha1, alpha2, alpha3, mu_pi, mu_Pi, baseline, pathways, rho)
}

updateGamma_cpp <- function(gamma, delta, Delta, A, B, L, alpha1, alpha2, alpha3, mu_pi, mu_Pi, baseline, pathways, rho) {
    .Call(`_BayesMAP_updateGamma_cpp`, gamma, delta, Delta, A, B, L, alpha1, alpha2, alpha3, mu_pi, mu_Pi, baseline, pathways, rho)
}

